name = "RingBufferDeque"
uuid = "52750b6a-75e1-4947-b5db-1ede328dde23"
authors = ["Alex Palmer <alex.palmer643@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
